### ISSUE TITLE
Überschreiben einer alten Hausnummer im ReorgAddressPlugin

### ISSUE THREAD

**Issue by Busfreak** [CCC-MF/onkostar-plugin-hl7address#1]
Aktuell wird das Splitten nicht durchgeführt, wenn im Feld Hausnummer etwas steht, was vom Hausnummernteil in Strasse abweicht.
Der Fall kann eintreten, wenn ein Patient mit getrennter Strasse und Hausnummer importiert wurde, nachher aber durch eine HL7-Nachricht aktualisiert wurde.
Beispiel:
importiert mit Strasse: Am Breitenstein, Hausnummer: 25
Patient ist umgezogen.
HL7-Nachricht: Strasse: Am Schlag 4
resultiernder Datensatz:
Strasse: Am Schlag 4, Hausnummer: 25

Hierbei muss durch das Plugin die Hausnummer überschrieben werden.

**Comment by pcvolkmer** [comment]
Es wurde ein Test hinzugefügt und das Szenario nachgestellt:

https://github.com/CCC-MF/onkostar-plugin-hl7address/blob/dfea6be031492a2a801bf9376aece8faa5b2ded8/src/test/java/de/ukw/ccc/onkostar/hl7address/Hl7AddressPluginTest.java#L75

Gemäß Testergebnis wird für den Fall, dass
* Eine Anschrift mit Straße `Am Breitenstein` und Hausnummer `25` für einen Testpatienten existiert
* Eine HL7-Nachricht mit Angabe `Am Schlag 4^^Musterhausen^^12345^DE` eingeht - siehe [`testhl7-2.hl7`](https://github.com/CCC-MF/onkostar-plugin-hl7address/blob/dfea6be031492a2a801bf9376aece8faa5b2ded8/src/test/resources/testhl7-2.hl7)
* Als neue Anschrift die Straße `Am Schlag` und Hausnummer `4` gespeichert.

Gibt es hier Abweichungen oder Besonderheiten in der HL7-Nachricht, die berücksichtigt werden müssen?

**Comment by Busfreak** [comment]
Das Szenario bezieht sich erstmal auf die ReOrg. HL7 kann ich derzeit noch nicht testen :-)

**Comment by pcvolkmer** [comment]
Also folgendes Szenario:

* Eine Anschrift mit Straße `Am Breitenstein` und Hausnummer `25` für einen Testpatienten existiert
* Eine HL7-Nachricht mit Angabe `Am Schlag 4^^Musterhausen^^12345^DE` geht ein - ohne Plugin
* Anschrift nun: 
  1. Straße `Am Schlag 4` und Hausnummer `<null>`/leer? Oder 
  2. Straße `Am Schlag 4` und Hausnummer `25`? - hier **ohne** Plugin und durch OS so - fehlerhaft - gespeichert.
* Aktivierung des Plugins und Reorganisation
* Anschrift nun: Straße `Am Schlag` und Hausnummer `4`

Sollte es durch Onkostar ohne Plugin als Straße `Am Schlag 4` gespeichert werden und Hausnummer `25` einfach beibehalten werden (Variante ii.), wäre dies ein Fehler in Onkostar.

Das Plugin erwartet, dass die Hausnummer leer ist und nicht irgend eine willkürliche Angabe oder ein altes "Adress-Artefakt" enthält:

* Straße `Am Schlag 4` und Hausnummer `4` => funktioniert, wird zu Straße `Am Schlag` und Hausnummer `4`
* Straße `Am Schlag 4` und Hausnummer `25` => wird ignoriert, da die aufgeteilte Hausnummer nicht zur bestehenden Hausnummer passt.

Siehe hier auch die Testdatenquelle: https://github.com/CCC-MF/onkostar-plugin-hl7address/blob/dfea6be031492a2a801bf9376aece8faa5b2ded8/src/test/java/de/ukw/ccc/onkostar/hl7address/ReorgAddressPluginTest.java#L118

Das Verhalten könnte jedoch angepasst werden um fehlerhafte "Hausnummern-Artefakte" zu überschreiben.

**Comment by pcvolkmer** [comment]
Branch `issue_1` mit Commit c4da1b7 enthält eine Änderung, die die fehlerhafte Hausnummer bei einer Reorganisation immer überschreibt, sofern eine neue Hausnummer im Inhalt der Zeichenkette der Straße erkannt wurde.

@Busfreak Das könnten wir so übernehmen um den Fehler in OS an dieser Stelle zu korrigieren.
