### ISSUE TITLE
ReorgAddressPlugin - Datensätze mit leerer Hausnummer werden nicht bearbeitet

### ISSUE THREAD

**Issue by Busfreak** [CCC-MF/onkostar-plugin-hl7address#3]
Das Abbruchkriterium für "Keine vollständige Adresse für Patient ..." enhält noch die Prüfung
null == address.getHouseNumber()

Diese sollte unterbleiben, wenn eine Hausnummer in der Strasse enthalten ist.

**Comment by pcvolkmer** [comment]
Das ist richtig, denn das Formularfeld kann auch einfach `null` sein, da es beim HL7-Import nicht angepasst wird und ansonsten solange leer bleibt, bis der Patient manuell bearbeitet wird. Erst dann wird dies durch eine (leere) Zeichenkette beim Speichern ersetzt.
